### ISSUE TITLE
Please fix the tree so it compiles

### ISSUE THREAD

**Issue by zamaudio** [brentp/vcfanno#101]
I have found a bug but I cannot contribute a fix because the tree does not compile out of the box.

Please rearrange your source tree so users can run "go install vcfanno".  You can do this quite easily by putting the source into ./src and adding all the required modules as git submodules (so you don't need to replicate source).  A simple makefile would be handy too.

Thanks

**Comment by brentp** [comment]
you can do `go build -o vcfanno vcfanno.go`. I am happy to accept a pull request that uses go modules (not git sub modules).
