### ISSUE TITLE
Field: FILTER not being added for gnomad annotations

### ISSUE THREAD

**Issue by cvlvxi** [brentp/vcfanno#104]
I'm noticing that when using the special FILTER keyword in the fields of my config that the filters are not being added but the special ID keyword is being added.

vcfanno.config

```
[[annotation]]
file="gnomad.genomes.r2.1.sites.vcf.gz"
fields = ["AF_popmax", "ID", "FILTER"]
ops = ["first", "self", "self"]
names = ["GNOMAD_AF_POPMAX", "GNOMAD_ID", "GNOMAD_FILTER"]
```

It produces this when I run it: 

```
vcfanno.go:114: found 3 sources from 1 files
vcfanno.go:166: Info Error: FILTER not found in header >> this error/warning may occur many times. reporting once here...
vcfanno.go:220: annotated 32 variants in 0.06 seconds (546.2 / second)
```

The gnomad vcf headers do contain FILTER headers but not sure why they would be relevant for copying the annotation

```
##FILTER=<ID=AC0,Description="Allele count is zero after filtering out low-confidence genotypes (GQ < 20; DP < 10; and AB < 0.2 for het calls)">
##FILTER=<ID=InbreedingCoeff,Description="InbreedingCoeff < -0.3">
##FILTER=<ID=PASS,Description="Passed all variant filters">
##FILTER=<ID=RF,Description="Failed random forest filtering thresholds of 0.2634762834546574, 0.22213813189901457 (probabilities of being a true positive variant) for SNPs, indels">
```

**Comment by brentp** [comment]
and you're using the latest release of vcfanno?

**Comment by cvlvxi** [comment]
Ah no I wasn't. Thanks for that. 👍

**Comment by brentp** [comment]
good. thanks for checking.

**Comment by ww2272** [comment]
Hi I am having the same issue and I am using the latest version of vcfanno.

**Comment by ww2272** [comment]
I tried the ID column and it works... I don't know why it's not working for FILTER...

**Comment by brentp** [comment]
can you provide a small vcf and annotation set to reproduce?

**Comment by ww2272** [comment]
[combined.vcf.gz](https://github.com/brentp/vcfanno/files/3834245/combined.vcf.gz)

Here's is the vcf file I am trying to annotate. I am just trying to annotate with the gnomAD 2.1.1 release exome and genome files. Thanks a lot!

**Comment by ww2272** [comment]
[vcfanno.txt](https://github.com/brentp/vcfanno/files/3836645/vcfanno.txt)

Here is the annotation configuration file I used.

**Comment by brentp** [comment]
vcfanno will not annotate the FILTER with variants that are PASS (or '.') in gnomAD; you'll only see the filter field for variants that are something other than PASS. does this match what you are seeing?

**Comment by ww2272** [comment]
Oh, I didn't know that. I will check! Thanks!
