### ISSUE TITLE
vcfanno is slient when the tabix index is older than the bed/vcf file 

### ISSUE THREAD

**Issue by zzupmc** [brentp/vcfanno#112]
Hi,

thanks for this excellent tool. I noticed that when the index file is older than the annotation file, the annotated vcf file has header information, but the variant line has no expected annotations.
```
##INFO=<ID=ClinPred_Score,Number=1,Type=Float,Description="calculated by max of overlapping values in column 6 from /home/pmi/share/genomes/Hsapiens/GRCh37/variation/clinpred.bed.gz">
```
 vcfanno is silent in this situation.

vcfanno version 0.3.1 [built with go1.11]
  

If you have encountered an error, please include:

- [ ] minimal conf and lua files that you are using.

[[annotation]]
file="/home/pmi/share/genomes/Hsapiens/GRCh37/variation/clinpred.bed.gz"
names = ["ClinPred_Score"]
columns = [6]
ops = ["max"]

- [ ] urls or actual files for annotations in conf file.
https://sites.google.com/site/clinpred/products-services

- [ ] minimal query file.

- [ ] the command you used to invoke vcfanno
/home/pmi/share/anaconda/bin/vcfanno -p 4  test.conf test.vcf.gz  |bgzip -c >test.anno.vcf.gz

- [ ] the **full** error message

vcfanno produces no error message

**Comment by brentp** [comment]
I have pushed a fix for this--it now outputs a warning if the index has been modified more recently than the data file--to an upstream dependency. thanks for reporting.
