### ISSUE TITLE
Multiple Files, Same Fields

### ISSUE THREAD

**Issue by violetbrina** [brentp/vcfanno#117]
It would be good to have a way to add multiple files to the "file" option in the config. For dbNSFP the vcfs are split up by chromosome but have the exact same column mapping.

If you could please add the option to make file an array like so:
>    [[annotation]]
    file="clinvar.norm.vcf.gz"
    fields=["FATHMM_score", "MetaSVM_score", "PROVEAN_score"]
    names=["FATHMM_score", "MetaSVM_score", "PROVEAN_score"]
    ops=["self", "self", "self"]

Thanks

**Comment by brentp** [comment]
For your dbNSFP, you can just use, e.g.:
```
[[annotation]]
file="dbnsfp.chr1.txt.gz"
fields=["FATHMM_score", "MetaSVM_score", "PROVEAN_score"]
names=["FATHMM_score", "MetaSVM_score", "PROVEAN_score"]
ops=["self", "self", "self"]

[[annotation]]
file="dbnsfp.chr2.txt.gz"
fields=["FATHMM_score", "MetaSVM_score", "PROVEAN_score"]
names=["FATHMM_score", "MetaSVM_score", "PROVEAN_score"]
ops=["self", "self", "self"]

....
```
and so on for each chrom. Does that address your problem?

**Comment by violetbrina** [comment]
Yeah that would work, and that's what I'm currently doing. 
I guess this is more a feature request for convenience more than anything else. Rather than copying and having to edit the mapping for each chromosome every time I make a change.

**Comment by brentp** [comment]
this is working as intended.
