### ISSUE TITLE
Extra "FORMAT" in the header line

### ISSUE THREAD

**Issue by liqg** [brentp/vcfanno#123]
I annotate a VCF file with only 1-8 columns (INFO only), however, the annotated VCF has an extra "FORMAT" field in the header line.
I have tested 0.3.3, 0.3.0 and 0.2.6. The same problem happened.

**Comment by brentp** [comment]
well, that's not good. for now, you'll have to pipe to `cut -f 1-8` and i'll get a fix for this out next month.

**Comment by dennishendriksen** [comment]
Ran into the same issue. I can probably work around it (bit tricky for my case because inputs sometimes contain samples/sometimes don't), but a fix would be appreciated @brentp :)

**Comment by brentp** [comment]
This is fixed in v0.3.4: https://github.com/brentp/vcfanno/releases/tag/v0.3.4
thanks for reporting.
