### ISSUE TITLE
does this warning mater?| WARNING: using op 'self' when with Number='1' can result in out-of-order values when the query is multi-allelic

### ISSUE THREAD

**Issue by liserjrqlxue** [brentp/vcfanno#128]
I annote ExAC 'AN_Adj' with op 'self' and got out-of-order warning:
```
api.go:811: WARNING: using op 'self' when with Number='1' for 'AN_Adj' from 'ExAC.r0.3.1.sites.vep.vcf.gz' can result in out-of-order values when the query is multi-allelic
api.go:812:        : this is not an issue if the query has been decomposed.
```
Does this mater for multi-allelic query now?

I checked [Annotate Clinvar With ExAC](http://brentp.github.io/vcfanno/examples/clinvar_exac/). It also use 'self' for ’AN_Adj'.

**Comment by brentp** [comment]
it's just a warning. If your vcf has REF=A and ALT=C,G and the clinvar vcf has a variant for A/C and A/G then your field with Number=1 will actually have 2 values.
In the annotate clinvar with ExAC example, both VCFs have been decomposed and normalized. That is the best way to be sure your annotations are consistent.

**Comment by liserjrqlxue** [comment]
Query vcf decomposed is not simple work for me.
I used `postannotation` to add `AF_Adj` and `AF_EAS` to ExAC itself and got a new file as annotate db.
I think this can solve this issue and annote fast.
