### ISSUE TITLE
Put FILTER in FILTER field, not INFO

### ISSUE THREAD

**Issue by bangbangphil** [brentp/vcfanno#130]
Hi,

Is there a way to write to FILTER field column? I know I can get FILTER fields from the input VCF writtten in INFO as a list value, put what I would need is to write a particular FILTER tag from the input VCF into the FILTER column of the output VCF. Is that possible?

thank you for your help,

Philippe

**Comment by brentp** [comment]
Hi, that's not possible. You'd have to use a downstream script to take the (newly added) filter from the INFO and put it in the FILTER field.

**Comment by bangbangphil** [comment]
Ah ok, guess I'll do just that. Thanks for the quick reply!
________________________________
De : Brent Pedersen <notifications@github.com>
Envoyé : 3 novembre 2020 09:00
À : brentp/vcfanno <vcfanno@noreply.github.com>
Cc : Philippe <bangbangphil@hotmail.ca>; Author <author@noreply.github.com>
Objet : Re: [brentp/vcfanno] Put FILTER in FILTER field, not INFO (#130)


Hi, that's not possible. You'd have to use a downstream script to take the (newly added) filter from the INFO and put it in the FILTER field.

**Comment by brentp** [comment]
no problem. I do see the utility of what you are requesting, but I don't want vcfanno to collapse under its own complexity.
