### ISSUE TITLE
Filtering whilst annotating. 

### ISSUE THREAD

**Issue by tirohia** [brentp/vcfanno#133]
Is there a way to access the vcf calls on a per-record basis as they are being annotated? Specifically, I'm looking for a way to retain only those vcf calls that have been annotated from at least one source. Don't know if this is possible, or if I have to filter out unannotated calls in a later step? 

Thanks
Ben.

**Comment by brentp** [comment]
hi, vcfanno will only annotate, not filter. so you'd have to use a downstream tool like bcftools or [slivar](https://github.com/brentp/slivar) to do the filtering.
