### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by sigven** [brentp/vcfanno#14]
Hi @brentp ,

Having downloaded the latest binaries, the too many open files problem has returned. For me, vcfanno works with the Linux binary you created for me previously (http://home.chpc.utah.edu/~u6000771/vcfanno_09b), but not with the latest release.

best,
Sigve

**Comment by brentp** [comment]
could you re-run prefixed by IRELATE_VERBOSE=TRUE
with this binary: http://home.chpc.utah.edu/~u6000771/vcfanno_0.10f
if it still fails, will you let me know the last 40 or so lines to STDERR?

I've tried to recreate this but am unable to do so this time. I guess you could also check the limits of

```
$ ulimit -Hn
$ sysctl fs.file-max
```

but even if I set those quite low, I'm not able to see the error.

**Comment by brentp** [comment]
... I'll try with the release version and see if I can recreate.

**Comment by brentp** [comment]
@sigven I am able to re-create with version 0.09 release. but not with the binary that I linked above. I'm working on adding a test-case for this but, it's fixed in master.

**Comment by sigven** [comment]
@brentp thanks. I ran with the 0.10f binary, and it did not fail now. btw, do you have a similar binary for Mac (darwin)?

**Comment by brentp** [comment]
thanks for checking. I'll make a pre-release shortly and CC this issue.

**Comment by brentp** [comment]
... and the pre-release will have a mac binary.

**Comment by brentp** [comment]
I published a pre-release that's solves this and a number of other smaller issues. Please let me know if you have any more problems.
