### ISSUE TITLE
[Typo] JavaScript function?

### ISSUE THREAD

**Issue by thephoenixofthevoid** [brentp/vcfanno#141]
It seems like a typo, but having js as an alternative is very interesting.

https://github.com/brentp/vcfanno/blob/9f857a9ad23ac80f76ae23ca06d3c619f08db0e0/vcfanno.go#L60

**Comment by brentp** [comment]
fixed .thanks. originally, vcfanno used javascript, but that engine was much slower.

**Comment by thephoenixofthevoid** [comment]
In a quick search I discovered this bindings https://github.com/augustoroman/v8
If it's possible to use these, it must be giving more performance. What do you think?

**Comment by brentp** [comment]
Hi, it's certainly an option for future projects, but I won't be doing that for vcfanno. By now, any users are dependent on the lua and there's no great reason to change.
There's also no guarantee that the overhead of calling into C would be small enough to negate any benefit from the V8 performance.

**Comment by thephoenixofthevoid** [comment]
Also: https://github.com/rogchap/v8go
If it's possible to make executor pluggable, that would be a solution.

**Comment by thephoenixofthevoid** [comment]
Also, It's very strange that lua code cannot be written inside a config. Would you like a PR with a feature of specifying it inside config?

**Comment by brentp** [comment]
The lua code can be specified inside of a file. 
If you're addressing a real problem, I'm happy to consider the issue and brainstorm a solution.

**Comment by thephoenixofthevoid** [comment]
I would like to have everything except maybe basepath to be specifiable via toml config. I checked a simple solution using triple-" syntax and it worked, but I think it's possible to do it in a more elegant way (consider a single file format of Vue as an example for the idea). Don't know if it falls into the category of real problems, just want  to have fewer arguments to pass and files to maintain.
