### ISSUE TITLE
Strategies to speed up?

### ISSUE THREAD

**Issue by FrankFeng** [brentp/vcfanno#144]
Hi,

I am using vcfanno with various annotation sources including big data like gnomAD and TOPMed. 

Will it be faster if I:

1. Split the source annotation file and the query VCF by chromosome. Annotation will be performed in parallel by chromosome. Each vcfanno job can use multiple cpu cores.

2. Convert source annotation from VCF to TSV. This can significantly reduce file size, because VCF includes key-value and TSV only has values.

Could you give me your opinion about this? Thanks!

**Comment by brentp** [comment]
Hi,
both of those should work, I think.

If you have data like gnomad or topmed, then you can get extremely fast annotation with [slivar](https://github.com/brentp/slivar) (and specifically, see more [here](https://github.com/brentp/slivar#gnotation-files).
slivar can annotate at >100K variants per second depending on the input file as most of the time is spent parsing and writing the input file as the annotations are in a binary format.
