### ISSUE TITLE
empty output

### ISSUE THREAD

**Issue by dKlee99** [brentp/vcfanno#145]
Hi, 

I have vcf produced by sniffles for SV calling and tried to annotate it with GFF but it produced an empty output.
The below is the bash command I ran. 

`vcfanno ./references/chm13.draft_v1.1.gene_annotation.v4.gff3 ./longread/samtools/T15/T15_chm13.vcf > vcfanno_annotated.vcf`
![image](https://user-images.githubusercontent.com/82995207/133060353-08e9fd58-0536-424e-8299-5f588f27dec2.png)

Your help is very much appreciated!

**Comment by brentp** [comment]
vcfanno takes a conf file that indicates the files and columns, not a gff. you should see an error message if you run like this.

**Comment by dKlee99** [comment]
Hi, thanks for your reply! It didn't show any error messages
