### ISSUE TITLE
Does vcfanno support NCBI RefSeq IDs?

### ISSUE THREAD

**Issue by CynthiaChuang** [brentp/vcfanno#153]
Hi Brent,

I'm new to this field and I have some questions. Hope you can can help me out.

We downloaded the reference sequence from NCBI and used vcfanno to annotate the produced VCF file. However, we did not get any annotation results. 

We suspect that the failure may be caused by the NCBI RefSeq ID?

![image](https://user-images.githubusercontent.com/17717355/220853015-8a8a27ca-a2dc-48bc-babb-b6ae453f39d7.png)

In the paper, the inconsistent chromosome labeling was mentioned with only "chr1" and "1" were given, while "NC_000001.11" was not mentioned. Does this mean that "NC_000001.11" is not supported and we need to use other tools such as bcftool to convert it in advance?

Or if vcfanno does support this labeling, what additional settings do we need to make when running it?

PS. conf_GRCh38.toml 
```
[[annotation]]
file="/usr/local/vcfanno/variants_GRCh38/clinvar.vcf.gz"
fields=["AF_ESP","AF_EXAC","AF_TGP","ALLELEID","CLNDN","CLNDNINCL","CLNDISDB","CLNDISDBINCL","CLNHGVS","CLNREVSTAT","CLNSIG","CLNSIGCONF","CLNSIGINCL","CLNVC","CLNVCSO","CLNVI","DBVARID","GENEINFO","MC","ORIGIN","RS","SSR"]
ops=["self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self"]
names=["clinvar_AF_ESP","clinvar_AF_EXAC","clinvar_AF_TGP","clinvar_ALLELEID","clinvar_CLNDN","clinvar_CLNDNINCL","clinvar_CLNDISDB","clinvar_CLNDISDBINCL","clinvar_CLNHGVS","clinvar_CLNREVSTAT","clinvar_CLNSIG","clinvar_CLNSIGCONF","clinvar_CLNSIGINCL","clinvar_CLNVC","clinvar_CLNVCSO","clinvar_CLNVI","clinvar_DBVARID","clinvar_GENEINFO","clinvar_MC","clinvar_ORIGIN","clinvar_RS","clinvar_SSR"]
```

Best, 
Cynthia

**Comment by brentp** [comment]
Hi Cynthia,
vcfanno will match "chr1" and "1", for example, but will not look up the NCBI names. I think you can convert those as described here: https://github.com/dpryan79/ChromosomeMappings and then use vcfanno. Otherwise, you'll have to find the original annotation file with the more usual chromosome names.

**Comment by CynthiaChuang** [comment]
Hi Brent,

Got it, thank you very much.

Best, Cynthia
