### ISSUE TITLE
Filtering variants by CADD value or nonsynonymous_SNV from annotated VCF file with Annovar 

### ISSUE THREAD

**Issue by alanmejiamaza** [brentp/vcfanno#157]
Hi,

I am a newbie using Annovar and just encountered this. I have annotated a vcf file, following the instructions. I have noticed that CADD_phred has dots for some variants and numbers for others.
CADD_phred=. 
CADD_phred=0.047
I think this is OK, as I have seen that in some blogs. Can you confirm this?
Now I am trying to filter by CADD>20 using this command using bcftools/1.11:
bcftools view -i "INFO/CADD_phred>20" -Oz -o out.vcf.gz in.vcf.gz
This is the error message:
Error: cannot use arithmetic operators to compare strings and numbers

I have tried to change the header for CADD_phred from string to float and invoked the above command, but it didn't work.
##INFO=<ID=CADD_phred,Number=.,Type=String,Description="CADD_phred annotation provided by ANNOVAR">
##INFO=<ID=CADD_phred,Number=.,Type=Float,Description="CADD_phred annotation provided by ANNOVAR">

I am also trying to filter variants by nonsynonymous_SNV and stopgain but I haven't been successful.

Any idea how to proceed?
Thanks in advance

**Comment by brentp** [comment]
Hi, Is this related to vcfanno?

a . value means unknown or undefined. You should leave CADD_phred as Number if you are trying to use numeric comparison.

**Comment by alanmejiamaza** [comment]
ok. Thanks a lot.
