### ISSUE TITLE
use Number from source file when op == "self"

### ISSUE THREAD

**Issue by brentp** [brentp/vcfanno#16]
currently, we always use Number=1 except for Flag which has Number=0 by definition. When the user specifies op="self", we should propagate the Number from the source header definition to the annotated VCF.

**Comment by ljdursi** [comment]
I'd just like to +1 this; it makes it more or less impossible to directly use that field in a postannotation otherwise.

**Comment by brentp** [comment]
@ljdursi can you give an example that's causing the trouble? I hadn't thought of that.

**Comment by ljdursi** [comment]
In my case, I'm annotating a vcf with some (stranded) read count information, eg, `NormalEvidenceReads=2,5` and then trying to calculate totals and/or read fractions in a post annotation and it won't work; I have to do the annotation in one pass, edit the file to have the right Number, and then do the postannotation calculations in a second pass.  Which isn't the end of the world, but it took a while to figure out.

[example.tar.gz](https://github.com/brentp/vcfanno/files/161888/example.tar.gz)

**Comment by brentp** [comment]
perfect. this is a great example; thank you for putting it together. FWIW, you could write a lua function that expects a string and just splits on "," and then does the division.
But, I'll get this fixed for the next release.

**Comment by ljdursi** [comment]
Great, thanks!  I tried having a lua function that takes a string, but couldn't get it to work with this example.. 

custom.lua:
```
function listsum(s)
    local sum=0
    for match in s:gmatch("([%d%.%+%-]+),?") do
        sum = sum + tonumber(match)
    end
    return sum
end
```

readcount.conf:
```
...
[[postannotation]]
fields = ["NormalEvidenceReads"]
op="lua:listsum(NormalEvidenceReads)"
name="TotalNormalEvidenceReads"
type="Integer"
```

```
$ vcfanno -lua custom.lua readcount.conf input.vcf > output.vcf
[...]
vcfanno.go:112: found 7 sources from 1 files
api.go:434: lua error in postannotation TotalNormalEvidenceReads <string>:3: attempt to index a non-table object(number)
stack traceback:
	<string>:3: in function 'main chunk'
	(tailcall): ?
	[G]: ?
vcfanno.go:157: strconv.ParseInt: parsing "0,1": invalid syntax >> this error may occur many times. reporting once here...
```

but that may be my underdeveloped lua (and/or vcfanno) skills.

**Comment by brentp** [comment]
You could try:

```lua
function split(str, sep)
        local sep, fields = sep or ":", {}
        local pattern = string.format("([^%s]+)", sep)
        str:gsub(pattern, function(c) fields[#fields+1] = c end)
        return fields
end

function listsum(k)
      local parts = split(parts, ",");
      return tonumber(parts[1]) + tonumber(parts[2])
end
```

**Comment by brentp** [comment]
Hi @ljdursi ,
I have just pushed a fix for this. You can get a linux 64 bit binary here:
http://home.chpc.utah.edu/~u6000771/vcfanno_0.11_linux
Let me know if you would be willing to try that out and/or if you need a mac binary.

The changes address the case when "self" is used as the op. For my own benefit, here are some notes... There are other cases where things might not work as expected by setting Number=1.

If the conf is like:
```
[[annotation]]
file="input.vcf.gz"
fields=["field_a"]
ops=["concat"]
```

then the user might want to `concat` with commas and set "Number=.". 

If it seems like there's enough of a use for this, then we could introduce an addition field for each `annotation` block so that it would look like:

[[annotation]]
file="input.vcf.gz"
fields=["field_a"]
ops=["concat"]
numbers=["."]
```

although, then, it might make the most sense to have a `types=` as well.
I think this might be rare enough that it's not needed. 
An alternative would be to always set Number="." when `op` is concat or uniq.

Actually, I think that is the best idea since all other operations should, by definition, return a single value.
This will break backwards compat because currently concat and join use "|" as the joiner.

**Comment by ljdursi** [comment]
Fantastic, thanks; I never did succeed in getting the treat-it-as-a-string option to work.

**Comment by brentp** [comment]
This is now in master along with setting Number=. for concat and uniq.
A binary with these changes is here:
http://home.chpc.utah.edu/~u6000771/vcfanno_0.11a_linux
thanks.
