### ISSUE TITLE
"go build" with freshly cloned repo: irelate go package error

### ISSUE THREAD

**Issue by brainstorm** [brentp/vcfanno#17]
Running go 1.5.3 and 1.6 I'm getting the following errors when trying to build/install what's in `master` for vcfanno:

```
mba-2:vcfanno romanvg$ go build -o vcfanno
# github.com/brentp/irelate/parsers
../../go/src/github.com/brentp/irelate/parsers/bam.go:196: assignment count mismatch: 2 = 1
../../go/src/github.com/brentp/irelate/parsers/bam.go:198: undefined: index.ErrInvalid

mba-2:vcfanno romanvg$ go get github.com/brentp/irelate
# github.com/brentp/irelate/parsers
../../go/src/github.com/brentp/irelate/parsers/bam.go:196: assignment count mismatch: 2 = 1
../../go/src/github.com/brentp/irelate/parsers/bam.go:198: undefined: index.ErrInvalid
```

**Comment by brentp** [comment]
do you have an older version of biogo/hts ? there is a relatively recent change that defines index.ErrInvalid (https://github.com/biogo/hts/commit/ecd52c98ba5b784479edf778b80ab8b9abba946e)

you can update with:
```
go get -u "github.com/biogo/hts/..."
```

**Comment by brainstorm** [comment]
Doh, totally forgot about biogo. Last time I was playing with it was last year :-S

Thanks Brent, worked like a charm, thanks for your patience!

**Comment by brentp** [comment]
great! let me know if you have any issues.
