### ISSUE TITLE
Append to existing INFO tag

### ISSUE THREAD

**Issue by sigven** [brentp/vcfanno#19]
Hi,

Is there an operation that allows you to append an annotation to an already existing tag in your query VCF. Let's say you have an ID tag in your query VCF, and there exists an ID tag in the annotation VCF also. Currently, it appears as if the query VCF tag is overwritten if it appears in the annotation VCF. Is there functionality to append/aggregate tag values if an existing tag is already present in your query?

best,
Sigve

**Comment by brentp** [comment]
So, that's possible combining with `[[postannotation]]`, for example pulling CIGAR from example/query.vcf.gz in the repo and annotating itself:

```
[[annotation]]
file="example/query.vcf.gz"
ops=["self"]
names=["newCIGAR"]
fields=["CIGAR"]

[[postannotation]]
fields=["CIGAR", "newCIGAR"]
op="lua:CIGAR .. ',' .. newCIGAR[1]"
name="CIGAR"
type="String"
```

So, first pull in the like-named field and give it a new name, then overwrite the original name in the `[[postannotation]]` section.

Maybe I'll make a `delete` or `drop` operation available for `[[postannotation]]` as this will leave a hanging `newCIGAR` field that's likely not used.

Thoughts?

**Comment by brentp** [comment]
@sigven , thoughts?

**Comment by sigven** [comment]
Hi,

That should work, I am sorry haven't had the time to test it properly yet. You can close the issue for now.

**Comment by brentp** [comment]
no problem. I'll leave it open as a placeholder for `drop` / `delete` which might be useful ops.

**Comment by brentp** [comment]
closing this. please re-open if your issue is not addressed.
