### ISSUE TITLE
Truncated annotations

### ISSUE THREAD

**Issue by dgaston** [brentp/vcfanno#21]
I'm running into a bizarre issue that at least so far seems to be tracing back to one particular variant found in Clinvar (chr7:140481403 C>A). When annotating a VCF that contains this variant I end up getting a truncated annotation info line on the output. (I see clinvar_significance= with no value followed by a tab and then the genotype fields).

Using clinvar_20160203.tidy.vcf and vcfanno 0.10

I have attached my vcfanno.conf and vcfanno.lua files, which are only slight modifications of those that were posted for basically the full GEMINI style annotation sources.

[test_files.zip](https://github.com/brentp/vcfanno/files/246951/test_files.zip)

**Comment by brentp** [comment]
looking into it now. probably a unicode thng that variant has "Malignant_lymphoma\x2c_non-Hodgkin|Rasopathy"

**Comment by dgaston** [comment]
Yup, that is probably the issue. I didn't catch the character when scanning through the line in the VCF.

**Comment by brentp** [comment]
can you try this for the clinvar_sig function

```
function clinvar_lookup(vals)
    local t = type(vals)
    -- just a single-value
    if(t == "string" or t == "number") and not contains(vals, "|") then
        return CLINVAR_LOOKUP[vals]
    else
        if not contains(t, "userdata") then
            vals = {vals}
        else
            vals = intotbl(vals)
        end
    end
    local ret = {}
    for i=1,#vals do
        if not contains(vals[i], "|") then
            ret[#ret+1] = CLINVAR_LOOKUP[vals[i]]
        else
            local invals = split(vals[i], "|")
            local inret = {}
            for j=1,#invals do
                inret[#inret+1] = CLINVAR_LOOKUP[invals[j]]
            end
            ret[#ret+1] = join(inret, "|")
        end
    end
    return join(ret, ",")
end
```

**Comment by brentp** [comment]
scratch that. doesn't fix the issue.

**Comment by brentp** [comment]
ok. this one fixes for me. 

```
function clinvar_sig(vals)
    local t = type(vals)
    -- just a single-value
    if(t == "string" or t == "number") and not contains(vals, "|") then
        return CLINVAR_SIG[vals]
    elseif t ~= "table" then
        if not contains(t, "userdata") then
            if t == "string" then
                vals = split(vals, ",")
            else
                vals = {vals}
            end
        else
            vals = intotbl(vals)
        end
    end
    local ret = {}
    for i=1,#vals do
        if not contains(vals[i], "|") then
            ret[#ret+1] = CLINVAR_SIG[vals[i]]
        else
            local invals = split(vals[i], "|")
            local inret = {}
            for j=1,#invals do
                inret[#inret+1] = CLINVAR_SIG[invals[j]]
            end
            ret[#ret+1] = join(inret, "|")
        end
    end
    return join(ret, ",")
end
```

and the corresponding clinvar_lookup:

```
function clinvar_lookup(vals)
    local t = type(vals)
    -- just a single-value
    if(t == "string" or t == "number") and not contains(vals, "|") then
        return CLINVAR_LOOKUP[vals]
    elseif t ~= "table" then
        if not contains(t, "userdata") then
            vals = {vals}
        else
            vals = intotbl(vals)
        end
    end
    local ret = {}^[[>1;3409;0c
    for i=1,#vals do
        if not contains(vals[i], "|") then
            ret[#ret+1] = CLINVAR_LOOKUP[vals[i]]
        else
            local invals = split(vals[i], "|")
            local inret = {}
            for j=1,#invals do
                inret[#inret+1] = CLINVAR_LOOKUP[invals[j]]
            end
            ret[#ret+1] = join(inret, "|")
        end
    end
    return join(ret, ",")
end
```

**Comment by dgaston** [comment]
I'm getting an error thrown from the clinvar_lookup: 

vcfanno -p 4 --lua /mnt/shared-data/ddb-configs/vcfanno.lua /mnt/shared-data/ddb-configs/vcfanno-myeloid.conf TM13.snpEff.GRCh37.75.vcf > ../VCFAnno/TM13.vcfanno.snpEff.GRCh37.75.vcf

=============================================
vcfanno version 0.0.10 [built with devel +387d5b8 Sat Feb 13 17:33:22 2016 +0000]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:112: found 60 sources from 18 files
api.go:116: error parsing custom lua:<string> line:118(column:12) near 'else':   syntax error

The else (line 118) is from this: in the fore loop:
```
for i=1,#vals do
        if not contains(vals[i], "|") then
            ret[#ret+1] = CLINVAR_LOOKUP[vals[i]]
        else
            local invals = split(vals[i], "|")
            local inret = {}
            for j=1,#invals do
                inret[#inret+1] = CLINVAR_LOOKUP[invals[j]]
            end
            ret[#ret+1] = join(inret, "|")
        end
    end
```

**Comment by brentp** [comment]
can you upload your entire vcfanno.lua ?

**Comment by dgaston** [comment]
Don't think I made any changes to it except for the two altered functions you posted.


[vcfanno.lua.txt](https://github.com/brentp/vcfanno/files/247402/vcfanno.lua.txt)

**Comment by brentp** [comment]
are you sure that's the file you're using? I don't get any parse-errors from that.

**Comment by dgaston** [comment]
Yeah, That's the version in my local repo, double checked the sync to my remote where I am running it. Just even did an scp from the remote server and diffed the files. Identical file.

**Comment by brentp** [comment]
remove the weird characters from my paste at line 114.

**Comment by dgaston** [comment]
Yup, that was was it. And the updated clinvar parsing corrects that issue on my files as well. Thanks

**Comment by brentp** [comment]
this is an unfortunate thing about using lua. requires a lot more defensive programming to get an error instead of failing silently. the unicode thing was a red-herring in this case. was actually just the lua code.

I'll leave this open til I update the lua in the repo.
