### ISSUE TITLE
-permissive-overlap per annotation block

### ISSUE THREAD

**Issue by dwaggott** [brentp/vcfanno#28]
Can this flag be applied per annotation or is it global? I'm debating running all annotations versus single annotation for simplified debugging.

**Comment by brentp** [comment]
it is global, for now, if you need both, you pipe from one to another:

```
vcfanno -permissive-overlap ... | vcfanno ... /dev/stdin/ ...
```

**Comment by dwaggott** [comment]
Ah very nice.
