### ISSUE TITLE
lua function on samples

### ISSUE THREAD

**Issue by dwaggott** [brentp/vcfanno#29]
Do you have any examples on how to call sample GT or PL format tags using a custom lua function? I'm looking for a way to annotation variants that are consistent with affection from a ped file. A binary flag or a super basic LOD score equivalent based on the genotype likelihoods is the plan.

**Comment by brentp** [comment]
This isn't possible right now, but not out of the question. It was raised in #15 . I'll give it some more thought but it won't be soon.

**Comment by dwaggott** [comment]
Thanks!
