### ISSUE TITLE
fault tolerance

### ISSUE THREAD

**Issue by dwaggott** [brentp/vcfanno#30]
I'm debating a single run per annotation vs multiple. Is vcfanno fault tolerant to failed steps i.e. for some reason an annotation was updated and it changed a tag name.

**Comment by brentp** [comment]
not sure what you mean, can you give an example or expand on the question?

**Comment by dwaggott** [comment]
If one of the annotations fails i.e. a missing file or tag, is there still a vcf output with the other annotation?

**Comment by brentp** [comment]
if a requested annotation file is completely missing, then it will fail. 
if, for example, only some of the lines from an annotation VCF contain a requested INFO field, then it will issue a warning but continue the annotation (since this can and will happen frequently).

**Comment by dwaggott** [comment]
Okay that's helpful. Time to give it a go!
