### ISSUE TITLE
REF/ALTs

### ISSUE THREAD

**Issue by roryk** [brentp/vcfanno#32]
Hi Brent,

Is there a way I can access the REF and ALT fields from the variant that is going to be updated in the lua scripts? I was hoping to annotate with a BED file by position but then make some decisions about whether or not to go ahead with the annotation based on REF/ALT information, namely is it a SNP and is it a specific mutation.

**Comment by brentp** [comment]
This is a good idea. I just added. It's available here: http://home.chpc.utah.edu/~u6000771/vcfanno_010_alpha

the lua variants ref and alt will be set and alt will be a table.

**Comment by roryk** [comment]
Damn, you are a beast. Thanks so much!

**Comment by brentp** [comment]
sure. let me know any other ideas or variables you might need to expose to lua.

**Comment by roryk** [comment]
Thanks-- is there some way I can set a flag when returning from a lua function rather than setting a value? I'm trying to take a BED file of edit sites from RADAR and mark up SNPs that overlap that edit-like mutations as possible edits.

**Comment by roryk** [comment]
Ah think I figured it out: prefixing with `flag` or `_flag` looks like it gets me what I was after. Sweet.

**Comment by brentp** [comment]
yes, you got it. the suffixing is a hacky way to do it, but works for now.
