### ISSUE TITLE
Problem with VCF file converted from BED

### ISSUE THREAD

**Issue by snashraf** [brentp/vcfanno#35]
I have a bed file and converted this into a fake VCF file like this 
##fileformat=VCFv4.0
#CHROM  POS     REF     ALT     INFO
1       762320  T       C       AC=10
1       783071  T       C       AC=10
1       879400  T       C      AC=10

and now I am trying to use VCFAnno on this and getting error as follows.
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT
panic: runtime error: slice bounds out of range

goroutine 53 [running]:
panic(0x80c7e0, 0xc420014140)
	/usr/local/src/go-git/src/runtime/panic.go:500 +0x1a1
github.com/brentp/vcfgo.makeFields(0xc4218c3600, 0x12, 0x13, 0x13, 0x13, 0x0)
	/usr/local/src/gocode/src/github.com/brentp/vcfgo/reader.go:156 +0x229
github.com/brentp/vcfgo.(*Reader).Read(0xc420502bc0, 0x0)
	/usr/local/src/gocode/src/github.com/brentp/vcfgo/reader.go:184 +0x107
github.com/brentp/irelate/parsers.vWrapper.Next(0xc420502bc0, 0x0, 0xfa0, 0xc424376000, 0x0)
	/usr/local/src/gocode/src/github.com/brentp/irelate/parsers/vcf.go:71 +0x2f
github.com/brentp/irelate.PIRelate.func4(0x1f40, 0xa59ca0, 0xc420502bc0, 0x8b0e00, 0x4e20, 0xc421ca8240, 0xc420502c80, 0x4, 0x4, 0xc420067900, ...)
	/usr/local/src/gocode/src/github.com/brentp/irelate/parallel.go:283 +0x14a
created by github.com/brentp/irelate.PIRelate
	/usr/local/src/gocode/src/github.com/brentp/irelate/parallel.go:346 +0x252

I am not sure why this is throwing this error. Can you please help on this.

**Comment by brentp** [comment]
A VCF will need these fields:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
```
you are missing ID, QUAL, and FILTER

**Comment by snashraf** [comment]
Thanks , It works for me. Actually I got confused with VCF example given at Github page. 
Thanks again for quick response .
