### ISSUE TITLE
CSQ tag

### ISSUE THREAD

**Issue by sigven** [brentp/vcfanno#36]
Hi,

I am trying to run vcfanno (v 0.0.11) against multiple VCF files using a query VCF coming from VEP annotation (Variant Effect Predictor). In the VEP output VCF file the CSQ tag is the only INFO tag, which is a String of potentially multiple values, in which each element contains fields separated by the pipe '|'. e.g. "CSQ= T|stop_gained|HIGH|ISG15|ENSG00000187608||||||,T|upstream_gene_variant|MODIFIER||||"

When I am running vcfanno using the VEP VCF file as query, the output VCF has the pipe separators of the CSQ tag converted into commas, which is quite inconvenient

e.g. after vcfanno: "CSQ= T,stop_gained,HIGH,ISG15,ENSG00000187608,,,,,,T,upstream_gene_variant,MODIFIER,,,,,"

I have made a work-around to get it working, but thought I'd check if you have any ideas about the reason for why it alters the query in this manner.

best,
Sigve

**Comment by brentp** [comment]
ouch. this is a problem. let me figure out how best to resolve.

**Comment by brentp** [comment]
@sigven, I run like this:
```
[[annotation]]
file="/data/gemini_install/data/gemini_data/ExAC.r0.3.sites.vep.tidy.vcf.gz"
fields=["CSQ"]
names=["csq2"]
ops=["self"]
```

and annotated ExAC with itself and didnt' see this. Are you using a lua function?

**Comment by sigven** [comment]
Ouch. my bad. My script included a sed command in the end that replaced the '|' with ',', apparently based on output in previous vcfanno versions. Do you use the '|' at all as a separator?

**Comment by brentp** [comment]
That's good!
we did use "|" in a previous version, but now it should use ",".
