### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by redcoon23** [brentp/vcfanno#37]
I was trying to run vcfanno(v 0.0.011) example file, but it return error messange as follow:

vcfanno.go:156: Info Error: lua_start not found in row >> this error may occur many times. reporting once here...

Could you provide any idea to solve this problem?

**Comment by brentp** [comment]
That's actually just a warning. I've improved the output message for the upcoming version. 
If you are on linux, you can get the binary here: https://github.com/brentp/vcfanno/releases/download/v0.1.0-dev/vcfanno

**Comment by brentp** [comment]
I'm going to close this issue. Let me know if you don't get the expected output (you should, despite the error messages).
