### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by roryk** [brentp/vcfanno#38]
Hi Brent,

Sorry to be that guy but any shot at a new release? We have some code using the new REF/ALT stuff but right now are grabbing the develop version by hand.

**Comment by brentp** [comment]
yeah, I'll try to get one out soon. I want to address #36, but I think everything else is good to go.

**Comment by roryk** [comment]
Thanks!

**Comment by brentp** [comment]
Hi @roryk , I just pushed a new release. Thanks!
