### ISSUE TITLE
go build --> undefined: interfaces.RandomGetter 

### ISSUE THREAD

**Issue by seandavi** [brentp/vcfanno#4]
Hi, Brent.  This project is exactly what I have been looking for.  

I'm just getting going with go, so this is probably my ignorance, but here is what the master branch shows on building....

```
$ go build
# github.com/brentp/vcfanno/api
../../brentp/vcfanno/api/api.go:164: o.Id undefined (type interfaces.IVariant has no field or method Id)
../../brentp/vcfanno/api/api.go:435: undefined: interfaces.RandomGetter
../../brentp/vcfanno/api/api.go:439: undefined: interfaces.RandomGetter
../../brentp/vcfanno/api/api.go:456: assignment count mismatch: 2 = 1
../../brentp/vcfanno/api/api.go:469: undefined: interfaces.RandomGetter
```

Any thoughts?

**Comment by brentp** [comment]
Hi Sean, I just saw this now. I've been breaking a lot of things and the master of this branch is relying on a non master branch of irelate.

If you either download the v0.0.7 binary or check out that tag, you should be good to go.

**Comment by brentp** [comment]
I just merged the stuff from the irelate that was causing this issue. You should be able to fix if you run

go get -u

**Comment by seandavi** [comment]
Thanks.  That did the trick.
