### ISSUE TITLE
Database not getting annotated with adjusted allele count from Exac 

### ISSUE THREAD

**Issue by komalsrathi** [brentp/vcfanno#40]
This is the conf:

```
[[annotation]]
file = "ExAC.r0.3.sites.vep.tidy.vcf.gz"
fields = ["AC_Adj", "AN_Adj"]
names = ["exac_ac_all", "exac_an_all"]
ops = ["min", "min"]

[[annotation]]
file = "grin/dbsnp137.coding.variants.sift.prediction.bed.gz"
columns = [14,15,18,19]
names = ["Provean_score","Provean_prediction","SIFT_score","SIFT_prediction"]
ops     = ["self", "self", "self", "self"]

[[annotation]]
file = "ESP6500SI.all.snps_indels.tidy.v2.vcf.gz"
fields = ["FG","AAC", "PH"]
names = ["functionGVS", "aminoAcidChange", "polyPhen"]
ops = ["self", "self", "self"]

[[annotation]]
file = "grin/literaturegenes_GRCh37.bed.gz"
columns = [4]
names = ["literature_genes"]
ops = ["self"]

[[annotation]]
file = "grin/recurrentgenes_GRCh37.bed.gz"
columns = [4]
names = ["recurrent_genes"]
ops = ["self"]

[[postannotation]]
fields = ["exac_ac_all", "exac_an_all"]
name = "exac_af_all"
op = "lua:divfunc(exac_ac_all[1],exac_an_all)"
type = "Float"
```

This is the lua:
```
function divfunc(a, b)
        if(a == 0) then 
                return 0.0
        else 
        return string.format("%.9f", a / b)
    end
end
```

When I create a geminidb, the database has exac_an_all and exac_af_all but not exac_ac_all. Why is that so?

If you have encountered an error, please include:

- [x] minimal conf and lua files that you are using.
- [ ] urls or actual files for annotations in conf file.
- [ ] minimal query file.
- [ ] the command you used to invoke vcfanno
- [ ] the **full** error message

**Comment by brentp** [comment]
what is the header line for `"exac_ac_all` in the annotated vcf?

**Comment by komalsrathi** [comment]
```
##INFO=<ID=exac_ac_all,Number=A,Type=Float,Description="calculated by min of overlapping values in field AC_Adj from /mnt/isilon/cbmi/variome/bin/gemini/data/gemini_data/ExAC.r0.3.sites.vep.tidy.vcf.gz">
##INFO=<ID=exac_af_all,Number=.,Type=Float,Description="calculated field: exac_af_all">
##INFO=<ID=exac_an_all,Number=1,Type=Float,Description="calculated by min of overlapping values in field AN_Adj from /mnt/isilon/cbmi/variome/bin/gemini/data/gemini_data/ExAC.r0.3.sites.vep.tidy.vcf.gz">
```

**Comment by brentp** [comment]
what version of vcfanno are you using? note that with Number=A, vcf2db can't know that all exac_ac_all entries have only 1 value so it reports an warning that it won't load that into the database.

the most recent vcfanno release should set Number=1 when you use min().

**Comment by komalsrathi** [comment]
Ok - I am using vcfanno version 0.0.11.

**Comment by brentp** [comment]
can you try with 0.1.0 and let me know.

**Comment by komalsrathi** [comment]
Sorry - I checked again and we are using the conda version which is 0.1.0: https://conda.anaconda.org/bioconda/linux-64/vcfanno-0.1.0-0.tar.bz2

**Comment by brentp** [comment]
ok. I checked and see that the error is indeed present. you can just change A to 1 in the header and it will load correctly. I'll leave this issue open until that is fixed.

**Comment by brentp** [comment]
I found the bug. If you use max instead of min, it will have Number=1 and max is likely more sensible for this scenario anyway.

**Comment by komalsrathi** [comment]
Thanks a lot!

**Comment by komalsrathi** [comment]
quick question - do I still need `exac_ac_all[1]` in `lua:divfunc(exac_ac_all[1],exac_an_all)`?

**Comment by brentp** [comment]
not if number=1
