### ISSUE TITLE
Not handling identical start/end coordinates

### ISSUE THREAD

**Issue by roryk** [brentp/vcfanno#41]
If you have encountered an error, please include:

- [x] minimal conf and lua files that you are using.
- [x] urls or actual files for annotations in conf file.
- [x] minimal query file.
- [x] the command you used to invoke vcfanno
- [ ] the **full** error message

Hi Brent,

vcfanno doesn't overlap coordinates if the start/end coordinates are identical, but bedtools does. 
I put up an example here: https://dl.dropboxusercontent.com/u/2822886/start-end-example.tar

Is bedtools or vcfanno doing it right?

**Comment by brentp** [comment]
HI Rory, this is a tough case. If it weren't a 0-lenght interval in the 60 bed file and it extended to the right, these would not overlap in bedtools. But, BT special-cases the 0-length interval.
Based on a rec from Aaron, I don't think I'll support that in vcfanno as it adds more confusion than it saves.

For your case, you can either manually add 1 to the end.

**Comment by roryk** [comment]
Thanks for following up. I fixed my BED files.
