### ISSUE TITLE
Float type with value "-0" in annoation VCF file becomes "-" in annotated VCF file

### ISSUE THREAD

**Issue by xuyangy** [brentp/vcfanno#42]
In ExAC database, variants with `InbreedingCoeff=-0;` becomes `InbreedingCoeff=-;` in the annotated VCF file. This causes later conversion to float giving an error message like "can't convert \- to float"

**Comment by brentp** [comment]
Hi, I have pushed a fixed for this. I'll make a pre-release of vcfanno. Would be great if you could verify that it fixes the problem  you are seeing.

**Comment by brentp** [comment]
The pre-release is up. Please let me know if it works for you.

**Comment by xuyangy** [comment]
It works!
