### ISSUE TITLE
tsv output

### ISSUE THREAD

**Issue by dwaggott** [brentp/vcfanno#47]
Can tsv's be output instead of vcf's?

**Comment by brentp** [comment]
No. This is outside the scope of vcfanno. It should be a relatively small matter to write  script to convert a VCF to tsv.

**Comment by crazyhottommy** [comment]
you can use gatk VariantsTotable https://software.broadinstitute.org/gatk/blog?id=7089

just be aware that if you have multiple samples in the vcf files, the order of the sample name is alphabetic http://gatkforums.broadinstitute.org/gatk/discussion/8760/gatk-variantstotable-output-ordering-of-tumor-and-normal-columns#latest

**Comment by crazyhottommy** [comment]
it is actually not that easy to convert a vcf to a tsv...if you annotated with both VEP and vcfanno.
after VEP, it adds CQS entry in the INFO field, 

```
e.g. INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|...
```
parsing it could be a mess..there are multiple isoforms annotated and there are could be empty values etc.

I found one script to convert the VEP annotated VCF to tsv  https://github.com/jwertz01/VCF-to-tab. but only works if you annotate the VCF with vcfanno and them VEP, because it assumes VEP CQS entry comes the last. Moreover, the output tsv column order seems to be random. 

In addtion, it did not pares the FORMAT column.

many times, I also want to extract the alternative counts and reference counts from the FORMAT column (GATK variants2table handles that):

```
GT:GQ:DP:AD:RO:QR:AO:QA:GL      0/1:58.6064:24:18,6:18:511:6:194:-10.5522,0,-39.0441 
```
A universal script to convert the vcf to tsv and extract all the necessary info column is needed.

My python skill is still limited..and could take days for a script. @brentp a golang script would be very helpful?

Thanks!
Tommy

**Comment by brentp** [comment]
I agree it would be useful, but this is outside the scope of `vcfanno`. If the VCF-to-tab does close to what you want, then I would modify that to your needs.

**Comment by crazyhottommy** [comment]
@brentp Thanks for offering help!

I uploaded several vcf files (changed the suffix to txt) for your test.

annotate with vcfanno and VEP:

https://gitlab.com/tangming2005/snakemake_DNAseq_pipeline/blob/freebayes_anno/Snakefile#L650

https://gitlab.com/tangming2005/snakemake_DNAseq_pipeline/blob/freebayes_anno/Snakefile#L665

custom `gem.conf` and `custom.lua` files (I copied most from a link sent by you) can be found: https://gitlab.com/tangming2005/snakemake_DNAseq_pipeline/tree/freebayes_anno

After converting the vcfanno and VEP annotated vcf to tsv:
https://gitlab.com/tangming2005/snakemake_DNAseq_pipeline/blob/freebayes_anno/Snakefile#L694


```bash
find *freebayes.tsv |parallel -k  'cat {} | head -1 | csvcut -nt | paste -s' | csvlook -t | less -S
```
columns are not of the same number for all the files:

```
  51: fitcons       |  52: encode_consensus_gm12878 |  53: encode_consensus_h1hesc |  54: encode_consensus_helas3 |  55: encode_consensus_h
+--------------------------+--------------+--------------------+-------------------------------+------------------------------+------------------------------+------------------------
|  49: technology.illumina |  50: SOMATIC |  51: fitcons       |  52: encode_consensus_gm12878 |  53: encode_consensus_h1hesc |  54: encode_consensus_helas3 |  55: encode_consensus_h
|  49: technology.illumina |  50: SOMATIC |  51: fitcons       |  52: encode_consensus_gm12878 |  53: encode_consensus_h1hesc |  54: encode_consensus_helas3 |  55: encode_consensus_h
|  49: technology.illumina |  50: SOMATIC |  51: fitcons       |  52: encode_consensus_gm12878 |  53: encode_consensus_h1hesc |  54: encode_consensus_helas3 |  55: encode_consensus_h
|  49: technology.illumina |  50: SOMATIC |  51: fitcons       |  52: encode_consensus_gm12878 |  53: encode_consensus_h1hesc |  54: encode_consensus_helas3 |  55: encode_consensus_h
|  49: technology.illumina |  50: SOMATIC |  51: ac_gnomad_all |  52: an_gnomad_all            |  53: af_gnomad_all           |  54: ac_gnomad_afr           |  55: an_gnomad_afr     
|  49: technology.illumina |  50: SOMATIC |  51: fitcons       |  52: encode_consensus_gm12878 |  53: encode_consensus_h1hesc |  54: encode_consensus_helas3 |  55: encode_consensus_h
|  49: technology.illumina |  50: SOMATIC |  51: fitcons       |  52: encode_consensus_gm12878 |  53: encode_consensus_h1hesc |  54: encode_consensus_helas3 |  55: encode_consensus_h
|  49: technology.illumina |  50: SOMATIC |  51: fitcons       |  52: encode_consensus_gm12878 |  53: encode_consensus_h1hesc |  54: encode_consensus_helas3 |  55: encode_consensus_h
|  49: technology.illumina |  50: SOMATIC |  51: fitcons       |  52: encode_consensus_gm12878 |  53: encode_consensus_h1hesc |  54: encode_consensus_helas3 |  55: encode_consensus_h
|  49: technology.illumina |  50: SOMATIC |  51: fitcons       |  52: encode_consensus_gm12878 |  53: encode_consensus_h1hesc |
```
I hope you can easily replicate this..

Thanks again!

[patient2_pre-treatment_vs_patient2_leukocyte_freebayes.txt](https://github.com/brentp/vcfanno/files/1258913/patient2_pre-treatment_vs_patient2_leukocyte_freebayes.txt)
[patient1_recurrence_vs_patient1_leukocyte_freebayes.txt](https://github.com/brentp/vcfanno/files/1258917/patient1_recurrence_vs_patient1_leukocyte_freebayes.txt)
[patient2_recurrence_vs_patient2_leukocyte_freebayes.txt](https://github.com/brentp/vcfanno/files/1258914/patient2_recurrence_vs_patient2_leukocyte_freebayes.txt)
[patient1_pre-treatment_vs_patient1_leukocyte_freebayes.txt](https://github.com/brentp/vcfanno/files/1258916/patient1_pre-treatment_vs_patient1_leukocyte_freebayes.txt)
[patient3_pre-treatment_vs_patient3_leukocyte_freebayes.txt](https://github.com/brentp/vcfanno/files/1258915/patient3_pre-treatment_vs_patient3_leukocyte_freebayes.txt)

**Comment by crazyhottommy** [comment]
forgot to mention that in the gen.conf I added dbsnp129 (the last dbsnp does not have contamination of the cancer SNVs), you can just use your own `gem.conf`.

Thanks!

Tommy

**Comment by brentp** [comment]
hi, sorry I was unclear. When I said 

> then I would modify that to your needs

I mean "then (if I were you) I would modify that to your needs. 

As I said, I agree this is useful. I just don't have the cycles to work on it now.

**Comment by crazyhottommy** [comment]
Hi @brentp  no problem at all! 
I understand it.
I will take a look then. 

Thanks again!
Tommy
