### ISSUE TITLE
annotate with multisample vcf

### ISSUE THREAD

**Issue by matthdsm** [brentp/vcfanno#48]
Hi Brent,

I'm looking to annotate an unannotated vcf file with allele frequencies from an existing multisample vcf. 
Is this something that's possible with vcfanno (I suppose so).

Would you be able to help with the configuration? I can't quite wrap my head around how calculate the allele frequency from the multisample vcf and add it to the new vcf.

EDIT: actually, I'd just like to add a field that contains in how many samples of the multisample vcf a certain variant is found.
Thanks
M

**Comment by brentp** [comment]
hi @matthdsm,
this isn't possible with vcfanno currently. I'll leave this issue open for thinking about how to do that, but I don't have any immediate plans for accessing the sample data in the FORMAT fields.

**Comment by matthdsm** [comment]
Hi Brent, 
Thanks for the reply!

On the same note, I'm looking for a way to annotate a vcf with a bed like file.
My file with annotations  looks as follows:
```
chrom   chromStart      chromEnd        AN_EOG  AC_EOG
chr1    10439   10439   2       AC:0&A:2
chr1    10442   10442   2       C:0&G:2
chr1    10448   10448   2       C:0&G:2
chr1    10460   10460   2       C:0&G:2
chr1    12807   12807   2       C:1&T:1
chr1    13273   13273   10      G:2&C:8
chr1    13302   13302   4       C:2&T:2
chr1    13417   13417   10      C:3&CGAGA:7
chr1    13418   13418   10      G:4&A:6
```
I'd like to annotate  with the last 2 columns. Should this do the trick?
```
[[annotation]]
file="EOG-AF.bed.gz"
names=["an_EOG","ac_EOG"]
columns=[4,5]
```
Or am I still missing some part?
Thanks for the help!
M

**Comment by brentp** [comment]
that looks right except you need to specify, e.g.
```
ops=['uniq', 'uniq']
```

**Comment by matthdsm** [comment]
Hi Brent,

Thanks again for the tip. Great little program you've got here, works blazingly fast compared to other tools out there. Are you open to any feature requests?
For one, I'd like to know if it would be possible to add a field to define the info type when annotating. Something like:
```
[[annotation]]
file="EOG-AF_v0.0.1a.bed.gz"
names=["an_EOG","ac_EOG"]
columns=[4,5]
type=["integer","integer"]
ops=["uniq","uniq"]
```
With as options `integer`, `float`,`string`,`flag`, cfr. the vcf standard. I think this would also benefit vcf2db, as the columns can then be designated the right type, instead of defaulting to `txt` of `varchar`.

Thank you for your thoughts.
M

**Comment by brentp** [comment]
so, if you use `max` or `min`, then it will make it a float.
I think you can also set the name as `an_EOG_float` and it will set type to float and strip "_float" from the name. but if your field looks like: `C:0&G:2` then you'd have to write a lua op to convert that to an int.

**Comment by matthdsm** [comment]
right! I'll give it a shot. thanks!

**Comment by matthdsm** [comment]
Hi Brent,

So the `max` and `min` do make the values `float`. Is there a way to make them `integer`? Or do I create a postannotation routine along the lines of:
```
[[postannotation]]
fields=["an_eog"]
op="lua: an_eog=an_eog"
name="an_eog"
type="Integer"

```

**Comment by brentp** [comment]
you can make them int by suffixing the names with "_int"

if you need to use lua, then you'll have to clarify what are the fields so I can help.

**Comment by matthdsm** [comment]
suffixing with _int made it work! Thanks!
Do you think you could add things like this to the readme or manual? 
Thanks again
M

**Comment by brentp** [comment]
yes, or I'll accept PRs. :)

**Comment by matthdsm** [comment]
Hi Brent,

I've tried the above approach to convert the values to "int", but in the resulting vcf, the suffix isn't parsed out. 

My config:
```
[[annotation]]
file="EOG-AF_v0.0.1a.bed.gz"
names=["an_EOG_int","ac_EOG"]
columns=[4,5]
ops=["max","uniq"]

[[annotation]]
file="EOG-GT_v0.0.1a.bed.gz"
names=["gc_hom_ref_EOG_int","gc_het_alt_EOG_int","gc_hom_alt_EOG_int"]
columns=[4,5,6]
ops=["max","max","max"]
```

Is there something wrong with the config? Or is this a genuine bug?

Thanks
M

**Comment by matthdsm** [comment]
apparently, the `ops` section overrules the column name parsing. When I change all of the `ops` to `uniq` instead of `max` all values get parsed as `int` and the name is adjusted.

**Comment by brentp** [comment]
I just pushed a fix for this. Thanks for the careful explanation. The logic to get the right type automatically is a bit sketchy, but it *does the right thing* most of the time. And now it's fixed to give the _int/_float/_flag suffixes preference over the ops.

**Comment by brentp** [comment]
... the release with this will be out later this month.

**Comment by matthdsm** [comment]
Hi Brent, 

Thanks for the fix! I think this will make this more clear for future users. Looking forward to the next release!

M
