### ISSUE TITLE
vcf - annotate by column possible?

### ISSUE THREAD

**Issue by colindaven** [brentp/vcfanno#50]
Hi,

thanks for the nice program and the nice easy conda installation.

I have a public VCF where I am interested in annotating my VCF using the publc ID field (rsID).

public VCF
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       4441    rs199073068     C       T       .       .       dbSNP_138;TSA=SNV;VE=intergenic_variant
1       4785    rs199337820     A       G       .       .       dbSNP_138;TSA=SNV;VE=intergenic_variant

my toml (are columns 0 or 1 based? )

testconf.toml
[[annotation]]
file="/home/colin/seqres/RN/var/Rattus_norvegicus_incl_consequences.vcf.gz"
columns = [2]
names = ["ID"]
ops=["first"]

Command:
vcfanno testconf.toml ../combined.vcf > combined_annot.vcf

So I just want to lift over the rsids (to start with, maybe INFO fields later) into my VCF. Is this possible ?

Thanks,
Colin

**Comment by colindaven** [comment]
Ah, I found this issue about the VCF ID. The second to last comment seems to have solved the problem!

https://github.com/brentp/vcfanno/issues/34

**Comment by brentp** [comment]
ok. let me know if you have any remaining questions.
