### ISSUE TITLE
Multiallelic sites

### ISSUE THREAD

**Issue by smottarella** [brentp/vcfanno#52]
Hi,

I have multiallelic input that I'd like annotated from data that will have multiple alleles per position. Obviously, I'd like the output the provide the correct values for only my input alleles returned in the correct order for analysis. I see you mention that the ability for vcfanno to handle this type of scenario is forthcoming, but suggest decomposing the inputs for now. However, my downstream application will require those sites to be recomposed before continuing. First, I'd like to make a formal request for this functionality to be completed, but in the meantime, do you have any suggestions for possibly decomposing, running vcfanno, then recomposing to get the same result as annotating multiallelic sites?

Thanks,
Scott

**Comment by brentp** [comment]
this is on the top of my list of things to add. I didn't build vcfanno with this in mind so it will likely be a large change. as such, it may be a few weeks.

**Comment by brentp** [comment]
I actually made some good progress on this. Should have a working version out this week.

**Comment by brentp** [comment]
this is out in the 0.2.0 release. please give it a try and let me know any issues.
thanks!
