### ISSUE TITLE
Sorting large VCF file fails

### ISSUE THREAD

**Issue by sa9** [brentp/vcfanno#61]
I am trying to annotate a 5+ Gb compressed VCF file with vcfanno but it fails at the sorting (after 10 min or so) with this message ```sort: write failed: /tmp/sortTH9eaK: No space left on device```

I tried fews things like
* changing the TMP folders for the sort command ($TMP=/new_temp_folder)
* adding -T option to sort (alias sort='sort -T /media/BML/tmp')

But the same issue persists. I know this is an OS issue not a vcfanno specific but I wonder where does vcfanno invoke the ```sort``` command and how can we change the default behavior?

-  the command used to invoke vcfanno
```./vcfanno_0.1.1   af_v1.tmol   d.vcf.gz  |  bgzip -c > o.vcf.gz ```

-  conf file.
[[annotation]]
file="ExAC.r0.3.sites.vep.decom_normalized_vt.vcf.gz"
fields = ["AF"]
names=["EXAC_AF"]

- the **full** error message

```=============================================
vcfanno version 0.1.1 [built with go1.8]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:114: found 2 sources from 2 files
sort -k1,1d -k2,2n
sort: write failed: /tmp/sortTH9eaK: No space left on device```

**Comment by brentp** [comment]
Hi, this isn't a vcfanno problem, your drive is full. You can see if there are other drives with more space with `df -h`

vcfanno doesn't call sort, so you must be doing that in the command-line, though it's not shown in your invocation above.
