### ISSUE TITLE
Feature: read from stdin

### ISSUE THREAD

**Issue by matthdsm** [brentp/vcfanno#67]
Hi Brent,

I don't know if this is technically possible, but how do you feel about enabling vcf input from STDIN?
It would be nice to be able to pipe output from VEP straight to vcfanno, without having to save an intermediate file.

Cheers
M

**Comment by brentp** [comment]
you can do this currently using `/dev/stdin` as the file handle. "-" might work as well.

**Comment by matthdsm** [comment]
oh, I wasn't aware this was already possible.

Thanks!
M
