### ISSUE TITLE
Separator of multiple hits and allele specific flag

### ISSUE THREAD

**Issue by kyasuno** [brentp/vcfanno#68]
Hi,

I need a help to annotate overlapping records per-allele basis when AC/AF in the source VCF is 
not available and multiple records in the source VCF could be matched to a single record of 
query VCF. 

I want to annotate my VCF file with dbSNP information from NCBI (All_*.vcf.gz) that 
contains RS and dbSNPBuildID fields. Both fields are of Number=1 and Type=Integer. 

It is possible that multiple records in All_*.vcf.gz could be matched to a single VCF record and 
they are currently annotated as

dbsnp_id=375757231,60722469;dbsnp_build=138,129 

even though the corresponding destination header says Number=1,Type=Integer inherited from 
the source file. 

Firstly, I think it is safer to use a separator different from a comma ',' for multiple hits to 
reserve the comma for multiple alleles/genotypes (Number=A,R,G). 

Secondly, I want to set the destination annotation as Number=A,Type=String so that 
we can know which allele matches the dbSNP record: In case where we have 2 ALT alleles, 
expected resulting annotation would be 
dbsnp_build=.,138|129  
when only the second allele matches dbSNP record. Is it possible to do in the 
framework of vcfanno? At minimum, can we specify destination type as Type=String in a 
similar way as typecasting (between float and int) explained in README?

Thanks
Katsuhito

**Comment by kyasuno** [comment]
I'm using the following config option:

fields=["RS", "dbSNPBuildID"]
ops=["self", "self"]
names=["dbsnp_id", "dbsnp_build"]

**Comment by brentp** [comment]
can you provide a small example? I think your second case should be handled.

I agree the the first point could be handled better, again, an example (test-case) would help me figure out how to address.

**Comment by kyasuno** [comment]
Yes, I attached an example here. Thanks for taking a look at this! 
Katsuhito

[vcfanno_example.tar.gz](https://github.com/brentp/vcfanno/files/1064766/vcfanno_example.tar.gz)

**Comment by kyasuno** [comment]
Another example (multi-allelic sites in query VCF hit multiple records in dbsnp). 

[ex2.tar.gz](https://github.com/brentp/vcfanno/files/1064821/ex2.tar.gz)

**Comment by brentp** [comment]
hi, this should be fixed in https://github.com/brentp/vcfanno/releases/tag/v0.2.7-beta
can you let me know if it resolves your issue?

**Comment by kyasuno** [comment]
Hi, 

Thanks for addressing this feature. 
I tested this version but it seems that only the first hit is captured and when query vcf has 
multiple ALTs, only 1 record is returned that breaks the rule (Number=A) 
(please see resulting (ex*_v0.2.7b.vcf) and log files in the attached tarball for details). 

Katsuhito

[vcfanno_test_data.tar.gz](https://github.com/brentp/vcfanno/files/1075947/vcfanno_test_data.tar.gz)

**Comment by brentp** [comment]
I see the issue. Thanks for the test-case. I'll get it fixed this week.

**Comment by brentp** [comment]
this is a hard problem.
to enumerate some of the gray areas:
suppose we have a query with:
```
123 A  T,C
```
for POS REF ALT.
then we have annotation of:
```
123 A T x=AAA
123 A C x=BBB
```
for that case, it's clear what should happen (annotate with AAA,BBB). But what if (this is one of your cases) you have an annotation of:
```
123 A T x=AAA
123 A T,C x=ZZZ,BBB
```
? 
if Number=A, then we can have only 2 values.

or of:
```
123 A T,C x=AAA,BBB
123 A T,C x=XXX,YYY
123 A C  x=TTT
```

I'm not sure how to resolve this in a reasonable way. we can and should handle the first case, but beyond that, I don't see a solution that will avoid future confusion.

**Comment by kyasuno** [comment]
I think that, apart from the complexity of implementation, 
it is possible to resolve this by changing the separator for multiple records. 
An expected output would be (here I use '|'):

123 A T,C x=AAA|ZZZ,BBB

This meets the Number=A requirement. 
However, we might always need to set Type=String in the output VCF regardless of 
the type given in annotation VCF.

**Comment by brentp** [comment]
so, I think if you're using self, then the best thing is to just maintain the $n slots and overwrite as newer entries come in. so, in the case of:

```
123 A T,C x=AAA,BBB
123 A T,C x=XXX,YYY
123 A C  x=TTT
```
it will first set the value to `AAA,BBB` then to `XXX,YYY` and the final value will be `XXX,TTT` (AAA,BBB will be overwritten and not output in the annotated VCF). 

I can't do what you are saying with `self` because that explicitly means to match the value and number of the annotation.
If you want to keep all values, you'll have to use concat, and if you need to know exactly where they came from, you could use a lua function.

Does this seem reasonable?

cc: @garrett-stevens

**Comment by brentp** [comment]
... and to clarify; for the schema i describe above. 
if the annotation is:
```
123 A T x=RRR
123 A C x=SSS
```
and the query is `123 A C,T`
then it will be annotated with `x=SSS,RRR`

**Comment by garrett-stevens** [comment]
@brentp,
Regarding your question back on #69, the warning was from the beta. Here's a complete output including the error:
```
=============================================
vcfanno version 0.2.7-beta [built with go1.8]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:115: found 2 sources from 1 files
api.go:216: WARNING: got single value %!s(float64=15.300000190734863) for value with Number=A
api.go:216: WARNING: got single value %!s(float64=1.7999999523162842) for value with Number=A
vcfanno.go:241: annotated 1 variants in 0.00 seconds (845.8 / second)
```

**Comment by brentp** [comment]
hmm. I thought I fixed the repr of the WARNING message.

can everyone interested weigh in on my proposed changes. I'm almost convinced that's the only transparent way to handle this.

**Comment by garrett-stevens** [comment]
I agree with you, keeping \# of slots = \# of ALT alleles and then overwriting with new values is the most straightforward way to handle this. I think it's the most general case and any special cases can be handled with concat, lua functions, etc.

**Comment by kyasuno** [comment]
I agree with the proposed change, too. 
To write a lua function according to the proposed change, 
a sort of multi-allelic version of concat, can I assume that the 
value from a single hit from an annotation VCF would be a vector of length #(ALT in query)?

Thanks
Katsuhito

**Comment by brentp** [comment]
I made a new pre-release that implements the specified behaviour here:
https://github.com/brentp/vcfanno/releases/tag/v0.2.7-beta2

@kyasuno I'll need to to more work (and thinking) on how to make the order and alts available to lua.

I think it could be that the lua will have to expect a function that accepts a table of tables,so if the query has 2 alts then:

```
[["some-value", "."], ["A", "B"]]
```

**Comment by garrett-stevens** [comment]
Latest pre-release is working great for me. Thanks!

**Comment by brentp** [comment]
@kyasuno I think that the best way to handle your case is to have a new op called `concat_with_alt` (name to be determined). so it does: `$val|$alt,...`.
e.g. `22|A,33|T,44|A`

so you know the alt associated with each value and each alt can have multiple values or no values. Does this work for you?

**Comment by brentp** [comment]
or it could be that the op is `by_alt`
then given:
123 A T,C x=AAA,BBB
123 A T,C x=XXX,YYY
123 A C  x=TTT
```

the result is:
```
T:AAA|XXX,C:BBB|YYY|TTT
```
so that Number=A in the output.

If in the annotation file Number=., then it won't track which annotation it came from. e.g.:
```
123 A T z=X,Y,Z
123 A T z=A,B,C
```

will result in:

```
T:X|Y|Z|A|B|C
```

I think I prefer this approach (even though I've just finished implementing the other.
thoughts?

**Comment by kyasuno** [comment]
Both concat_with_alt and by_alt work perfectly for me! Probably by_alt without specifying allele is 
better because it would keep minimal information without inflating VCF size unnecessarily (some long 
complex variants would cause some inconvenience if we keep the allele explicitly).

**Comment by brentp** [comment]
hi All, I've implemented `by_alt` as described above and made another (hopefully final) beta release here: https://github.com/brentp/vcfanno/releases/tag/v0.2.7-beta3

I'd appreciate if you could try it out and let me know any feedback. I really appreciate the discussion so far.

**Comment by garrett-stevens** [comment]
The new `by_alt` is looking good. I think it's a nice, straightforward way to handle the particular case of multiple annotations for an ALT. The only thing I noticed is it doesn't keep the same floating-point precision like `self` does. For example, with this setup:
```
123 G C a=1.8
123 G T a=2
123 G C a=11.8
123 G C a=22
```
If I use 'self' I get something like this:
```
123 G C,T a=11.8,22
```
which is perfect. Then if I use `by_alt` I get something like:
```
123 G C,T a=1.7999999523162842|11.800000190734863,2|22
```

The only other question I have is about the header. I noticed if my source is Type=Float, `by_alt` keeps it to be Type=Float. That makes sense to a certain extent, since it's just concatenating floats, but since it  adds the "|", it seems like maybe it should be Type=String? I'm not sure, though, and I don't have a workflow where the difference would matter to me.

**Comment by brentp** [comment]
@garrett-stevens Thanks! I have addressed both of these in latest commits.
I'll make a new full release today.

**Comment by brentp** [comment]
Hi All, new release is here: https://github.com/brentp/vcfanno/releases/tag/v0.2.7

thanks very much for all the feedback. Please let me know any other issues/features.

**Comment by kyasuno** [comment]
Thanks, this is really convenient.
