### ISSUE TITLE
Change header ##INFO description to "Number=A"?

### ISSUE THREAD

**Issue by garrett-stevens** [brentp/vcfanno#69]
When I annotate a VCF using another VCF as a source, for lines where there are multiple ALT alleles I get comma-separated values for each INFO ID, e.g. using CADD:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE1
1	16388580	rs3978467	C	A,T	350.2	.	cadd_phred=6,6.3;cadd_raw=0.3,0.4;	GT:AD:DP:GQ:PL	0/1:13,13,0:26:99:281,0,494,354,536,1067
```
This is exactly what I want. In the header tag that vcfanno adds, however, it has this:
```
##INFO=<ID=cadd_phred,Number=1,Type=Float,Description="phred-scaled cadd score (from ...)">
##INFO=<ID=cadd_raw,Number=1,Type=Float,Description="raw cadd score (from ...)">
```
It seems like this should be "Number=A", according to the VCF specs:
> If the field has one value per alternate allele then this value should be ‘A’.

I'm guessing it might just be copying this value from the source VCF (the source has "Number=1", probably because it expects all variants with multiple ALT alleles to be split into single lines). Is there a way to get vcfanno to change this value to "Number=A", since that's what it is in the newly annotated VCF?

Thanks

**Comment by brentp** [comment]
This is related to #68. I'll have a look at these next week.

**Comment by brentp** [comment]
can you give: https://github.com/brentp/vcfanno/releases/tag/v0.2.7-beta
a try and let me know if it resolves your issue.

**Comment by garrett-stevens** [comment]
I've been watching the discussion on #68, and it looks like I'm having the same problem (header is now Number=A, but it's now missing the annotation for the second ALT). I also got some warnings in the STDERR, all like:
```
api.go:216: WARNING: got single value %!s(float64=15.300000190734863) for value with Number=A
```
See the attached tar.gz for an full, minimal working example: [test.tar.gz](https://github.com/brentp/vcfanno/files/1076132/test.tar.gz)

I agree this is a tricky problem, but I am just fine with only the first case you describe in #68 being supported.

Thanks

**Comment by brentp** [comment]
that warning is from the last version of vcfanno, not the beta, right?

**Comment by brentp** [comment]
let's continue this in #68 to keep it centralized.
