### ISSUE TITLE
Does VCF anno strip FORMAT and GT fields after running?

### ISSUE THREAD

**Issue by indapa** [brentp/vcfanno#8]
I ran vcfanno on NA12878 for a small region. The FORMAT and GT fields are stripped in the result file.   Is this the desired behavior of the software? Here is before decoration:

```
chr22   42128241        .       CT      C       0       PASS    metal=platinum;isaac2=HD:0,LOOHD:0;bwa_freebayes=HD:0,LOOHD:0;bwa_platypus=HD:0,LOOHD:0;bwa_gatk3=HD:0,LOOHD:0;dist2closest=452 GT      0|1
```
Here is after:

```
chr22   42128241        .       CT      C       0.0     PASS    metal=platinum;isaac2=HD:0,LOOHD:0;bwa_freebayes=HD:0,LOOHD:0;bwa_platypus=HD:0,LOOHD:0;bwa_gatk3=HD:0,LOOHD:0;dist2closest=452;RSID=rs35742686;CYPALLELE=*3;HGVSc=NM_000106.5:c.2549delA
```

**Comment by brentp** [comment]
I didn't see this til now. I'll have this fixed for 0.8 release.

**Comment by indapa** [comment]
Great! Thank you! I'll check it out.

**Comment by brentp** [comment]
Hi @indapa I've updated this can you test if this executable addresses your problem: https://www.chpc.utah.edu/~u6000771/vcfanno_08a1
it's for 64bit linux

**Comment by brentp** [comment]
did this work for you?
