### ISSUE TITLE
multiple CADD annotations files

### ISSUE THREAD

**Issue by RoanKanninga** [brentp/vcfanno#83]
Is it, or would it be, possible to annotate with multiple CADD annotations file. 
Since the Indels have to be calculated most of the times we have a file with the calculated CADD scores for the indels and the whole_genome_SNVs file. 
The problem we encounter in annotators we use is that we have multisample vcf's and if there is e.g. at a certain location a SNP and an INDEL, then the annotation is wrong.
Example:
12   123456 .  A    AC,T

in this case there is a deletion of a C for a certain sample and another sample is an A/T SNP. What you would expect is to get for each variation comma seperated CADD scores (raw and phred). At this moment we did not find any annotator that solved this problem so far.
Is is possible to include 2 annotations file in one go?

**Comment by brentp** [comment]
Yes, just use a single conf file . something like:

```
[[annotation]]
file="cadd.tsv.gz"
names=["cadd_phred"]
columns=[4]
ops=["self"]

[[annotation]]
file="cadd_indels.tsv.gz"
names=["cadd_phred"]
columns=[4]
ops=["self"]
```
since they have the same name of `cadd_phred` the annotation will be sent to the same place in the INFO.

**Comment by RoanKanninga** [comment]
[testVcfAnno.tar.gz](https://github.com/brentp/vcfanno/files/2056817/testVcfAnno.tar.gz)

I hope you will have a solution for this problem

**Comment by RoanKanninga** [comment]
Hi Brent,
did you already look into the problem?

**Comment by brentp** [comment]
Hi, sorry for the delay. I have pushed a fix. Would you try the attached binary and let me know that it resolves this for you. I have used your data as a test-case added to the repo. Thanks very much for the clear explanation and simple test.
[vcfanno_linux64.gz](https://github.com/brentp/vcfanno/files/2073257/vcfanno_linux64.gz)

**Comment by RoanKanninga** [comment]
Great, it works!

**Comment by brentp** [comment]
great. thanks for getting back to me.

**Comment by e-271** [comment]
Hi, I'd like to re-open this issue. I am having the same problem using multiple CADD files to annotate a VCF, but my CADD files are in a tsv format. The updated vcfanno version still seems to overwrite annotations for multiple TSV files, although it works for multiple VCF files. Can you please help? I have included example files below. Thank you!

[testVcfannoTsv.tar.gz](https://github.com/brentp/vcfanno/files/12353494/testVcfannoTsv.tar.gz)

**Comment by brentp** [comment]
It's likely you've found what could be considered a bug. But this is, I think due to having the same name annotation in different files. You could get around this by combining the annotation files.
Otherwise, I suggest to use `bcftools norm` to decompose multiple alt alleles.
