### ISSUE TITLE
CNV and SV annotation

### ISSUE THREAD

**Issue by alphahmed18** [brentp/vcfanno#84]
Hi, 

Thanks again for the great tool and your appreciated help.

I wonder if you could include an example (config and lua files), on how to annotate CNVs and SVs? 

I'd be really useful too to suggest specific databases for CNVs and SVs that work the best with vcfanno?

Regards,
Ahmed

**Comment by brentp** [comment]
vcfanno will work out-of-the-box to annotate SV and CNVs. Do you have a more specific question?
