### ISSUE TITLE
Could vcfanno annotate mutation type ? like frame-shift/Premature-Stop for indel, Synonymous/Stop_nonsyn  for snp

### ISSUE THREAD

**Issue by orangeSi** [brentp/vcfanno#88]
Hi~
   Thanks for the nice vcfanno~
   Could vcfanno annotate mutation type ? like frame-shift/Premature-Stop for indel, Synonymous/Stop_nonsyn  for snp.

thanks~
Si

**Comment by brentp** [comment]
no. this is outside the scope of vcfanno. you can use VEP or snpEff or bcftools CSQ for this.
