### ISSUE TITLE
v1.4 of CADD header with '#chr' not '#chrom'

### ISSUE THREAD

**Issue by janakn** [brentp/vcfanno#91]
Not a severe error, but FYI:
I downloaded the CADD hg19 version 1.4 from http://cadd.gs.washington.edu/download 
--> I tried to convert it to vcf with this script, but it kept throwing the error: 
```
  File "cadd2vcf.py", line 46, in <module>
    main(a.precision, a.path)
  File "cadd2vcf.py", line 30, in main
    d = dict(zip(header, line.rstrip().split("\t")))
TypeError: zip argument #1 must support iteration

```
This was due to the header staying _None_ during the script, because the `line.lower().startswith("#chrom")` statement was never true.
The header in the file is: 
```
## CADD GRCh37-v1.4 (c) University of Washington, Hudson-Alpha Institute for Biotechnology and Berlin Institute of Health 2013-2018. All rights reserved.
#Chr    Pos     Ref     Alt     RawScore        PHRED
1       10001   T       A       0.118631        4.575
```
Issue was resolved when changing the following lines
1.
FROM:
`tmpl = "{chrom}\t{pos}\t.\t{ref}\t{alt}\t1\tPASS\traw={rawscore:.%if};phred={phred:.%if}" % (precision, precision)`
TO:
`tmpl = "{chr}\t{pos}\t.\t{ref}\t{alt}\t1\tPASS\traw={rawscore:.%if};phred={phred:.%if}" % (precision, precision)`
2. 
FROM:
`if header is None and line.lower().startswith("#chrom"):`
TO:
`if header is None and line.lower().startswith("#chr"):`

Please consider testing for '#chrom' and '#chr' in header~ 
Thank you!

**Comment by brentp** [comment]
that script is no longer needed. you can use the cadd file directly.

**Comment by janakn** [comment]
I am really sorry I missed that! 
Thanks for letting me know!

**Comment by brentp** [comment]
No problem. I should remove that script from the repo.
