### ISSUE TITLE
Pos(1-based) syntax error when annotation dbNSFP data

### ISSUE THREAD

**Issue by settys02** [brentp/vcfanno#93]
Hi, love the tool, thanks for your continued support on it!

I'm trying to annotate a set of variants with data from dbNSFP, but when I do I keep getting the following error:
panic: strconv.Atoi: parsing "pos(1-based)": invalid syntax

The original dbNSFP file I was using had pos(1-based) as the column name for the position, but I got rid of it and I still get the same error. I'll attach my conf file, and samples of the files with this post. 

orig_dbNSFP is a 100 line subset of the original file, modified dbNSFP is a 100 line subset of the file with my modification (got rid of the top columns names, standardized the delimiting), and conf_dbNSFP is the toml file I used (just renamed to .txt to upload)

[modified_dbNSFP.txt](https://github.com/brentp/vcfanno/files/2271700/modified_dbNSFP.txt)
[orig_dbNSFP.txt](https://github.com/brentp/vcfanno/files/2271702/orig_dbNSFP.txt)
[conf_dbNSFP.txt](https://github.com/brentp/vcfanno/files/2271706/conf_dbNSFP.txt)

**Comment by brentp** [comment]
if the error is `panic: strconv.Atoi: parsing "pos(1-based)": invalid syntax`
then you are still using a file with "pos(1-based)" somewhere in the file.

remember you need to update your conf file with the path to the new file that you made without the header.

**Comment by brentp** [comment]
> And there is no header in my dbNSFP source file, it starts directly at the second line.

then how does vcfanno know the header is "pos(1-coor)" ?

which you can see from the error:

> panic: strconv.Atoi: parsing "pos(1-coor)": invalid syntax

you must be pointing the conf file to a file **with** a header.

**Comment by weber8thomas** [comment]
Thank you for quick response !!!

Sorry I found my mistake, you were write, I merge different files which were splitted by CHR and remove the header only for the first of them.

However, thanks for your answer, we are currently moving from VEP with all his super slow plugins to VCFANNO which is super fast to annotate big VCF files :)

Thanks for the support !
